Numpy is a fundemental library for scientific computing in pyhton

In [6]:
import numpy as np
## create arrays using numpy
## create 1d array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [11]:
arr2=np.array([1,2,3,4,5])
print(arr2.reshape(1,5)) # 1 row and 5 columns
print(arr2.shape)

[[1 2 3 4 5]]
(5,)


In [15]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [18]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [22]:
print(np.zeros((3,4)))
print(np.ones((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
###  numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## element wise addition
print("Addition:\n",arr1+arr2)

## elements wise substraction
print("Substraction:\n",arr1-arr2)
## same for multiplication and division


Addition:
 [11 22 33 44 55]
Substraction:
 [ -9 -18 -27 -36 -45]


In [29]:
## universal function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))
## exponential
print(np.exp(arr))
#sine
print(np.sin(arr))
# 
# log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [36]:
## array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)
## accessing single elements from the array
arr[0][0]

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


np.int64(1)

In [44]:
print(arr[1:,2:])
print(arr[0:2,2:])

[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]


In [46]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [47]:
## modify array elements
arr[0,0]=100

In [48]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [49]:
arr[1:]=100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [50]:
### statistical concept --- normalization
## to have a mean of 0 and standard daviation of 1
data=np.array([1,2,3,4,5])

# calculate mean and standard daviation
mean=np.mean(data)
std_dev=np.std(data)

# normalize the data

normalized_data=(data-mean)/std_dev
print("Normalized data is: ",normalized_data)


Normalized data is:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [53]:
# mean median mod calculation of a given data
data=np.array([1,2,3,4,5,6,7,8,9,10])
# mean
mean=np.mean(data)
print("Mean of the given data is: ",mean)
# median
median=np.median(data)
print("Median of the given data is: ",median)
# standard daviation
std_dev=np.std(data)
print("Standard daviation of the given data is: ",std_dev)
# varience
var=np.var(data)
print("varience of the given data is: ",var)


Mean of the given data is:  5.5
Median of the given data is:  5.5
Standard daviation of the given data is:  2.8722813232690143
varience of the given data is:  8.25


In [57]:
## logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])